import type { Metadata } from "next";
import { Lusitana } from "next/font/google";
import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const libertinusMath = Lusitana({
  variable: "--font-libertinus-sans-regular",
  weight: "400",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "App Jokes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${libertinusMath.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
